In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
dframe = pd.read_csv('winequality-red.csv', sep=';')
dframe.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25,67,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15,54,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17,60,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5

In [3]:
def ranker(df):
    df['alc_content_rank'] = np.arange(len(df)) + 1
    return df

In [6]:
dframe.sort_values(by='alcohol', ascending=True, inplace=True)

In [9]:
dframe = dframe.groupby('quality').apply(ranker)

In [10]:
dframe.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
544,14.3,0.31,0.74,1.8,0.075,6,15,1.00080,2.86,0.79,8.4,6,1
517,10.4,0.61,0.49,2.1,0.200,5,16,0.99940,3.16,0.63,8.4,3,1
1436,10.0,0.38,0.38,1.6,0.169,27,90,0.99914,3.15,0.65,8.5,5,1
528,8.2,0.42,0.49,2.6,0.084,32,55,0.99880,3.34,0.75,8.7,6,2
371,7.9,0.24,0.40,1.6,0.056,11,25,0.99670,3.32,0.87,8.7,6,3

In [11]:
num_of_qual = dframe['quality'].value_counts()
num_of_qual

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [13]:
dframe[dframe.alc_content_rank == 1].head(len(num_of_qual))

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
544,14.3,0.31,0.74,1.8,0.075,6,15,1.00080,2.86,0.79,8.4,6,1
517,10.4,0.61,0.49,2.1,0.200,5,16,0.99940,3.16,0.63,8.4,3,1
1436,10.0,0.38,0.38,1.6,0.169,27,90,0.99914,3.15,0.65,8.5,5,1
18,7.4,0.59,0.08,4.4,0.086,6,29,0.99740,3.38,0.50,9.0,4,1
243,15.0,0.21,0.44,2.2,0.075,10,24,1.00005,3.07,0.84,9.2,7,1
440,12.6,0.31,0.72,2.2,0.072,6,29,0.99870,2.88,0.82,9.8,8,1